# Generated by Django 3.1.6 on 2021-03-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='cread_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
