# Generated by Django 3.1.6 on 2021-03-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210306_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='text',
            field=models.TextField(max_length=400),
        ),
    ]
